{
    "version": "1.1.403",
    "time": "1752520263725",
    "generalDiagnostics": [
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\admin.py",
            "severity": "error",
            "message": "Cannot access attribute \"last_login\" for class \"AnonymousUser\"\n┬á┬áAttribute \"last_login\" is unknown",
            "range": {
                "start": {
                    "line": 33,
                    "character": 29
                },
                "end": {
                    "line": 33,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"last_login\" for class \"AnonymousUser\"\n┬á┬áAttribute \"last_login\" is unknown",
            "range": {
                "start": {
                    "line": 34,
                    "character": 30
                },
                "end": {
                    "line": 34,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\admin.py",
            "severity": "error",
            "message": "No parameter named \"update_fields\"",
            "range": {
                "start": {
                    "line": 35,
                    "character": 35
                },
                "end": {
                    "line": 35,
                    "character": 48
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"short_description\" for class \"FunctionType\"\n┬á┬áAttribute \"short_description\" is unknown",
            "range": {
                "start": {
                    "line": 69,
                    "character": 13
                },
                "end": {
                    "line": 69,
                    "character": 30
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"admin_order_field\" for class \"FunctionType\"\n┬á┬áAttribute \"admin_order_field\" is unknown",
            "range": {
                "start": {
                    "line": 70,
                    "character": 13
                },
                "end": {
                    "line": 70,
                    "character": 30
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 29,
                    "character": 39
                },
                "end": {
                    "line": 29,
                    "character": 47
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 34,
                    "character": 32
                },
                "end": {
                    "line": 34,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\forms.py",
            "severity": "error",
            "message": "\"get\" is not a known attribute of \"None\"",
            "range": {
                "start": {
                    "line": 67,
                    "character": 31
                },
                "end": {
                    "line": 67,
                    "character": 34
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\forms.py",
            "severity": "error",
            "message": "\"get\" is not a known attribute of \"None\"",
            "range": {
                "start": {
                    "line": 68,
                    "character": 39
                },
                "end": {
                    "line": 68,
                    "character": 42
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\clear_database.py",
            "severity": "error",
            "message": "\"admin_username\" is possibly unbound",
            "range": {
                "start": {
                    "line": 174,
                    "character": 38
                },
                "end": {
                    "line": 174,
                    "character": 52
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\clear_database.py",
            "severity": "error",
            "message": "\"admin_email\" is possibly unbound",
            "range": {
                "start": {
                    "line": 178,
                    "character": 38
                },
                "end": {
                    "line": 178,
                    "character": 49
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\health_check.py",
            "severity": "error",
            "message": "Cannot access attribute \"keys\" for class \"BaseCache\"\n┬á┬áAttribute \"keys\" is unknown",
            "range": {
                "start": {
                    "line": 174,
                    "character": 29
                },
                "end": {
                    "line": 174,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 377,
                    "character": 68
                },
                "end": {
                    "line": 377,
                    "character": 70
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 379,
                    "character": 67
                },
                "end": {
                    "line": 379,
                    "character": 69
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 460,
                    "character": 106
                },
                "end": {
                    "line": 460,
                    "character": 108
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 496,
                    "character": 68
                },
                "end": {
                    "line": 496,
                    "character": 70
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "\"maintenance_activity\" is not a known attribute of \"None\"",
            "range": {
                "start": {
                    "line": 506,
                    "character": 26
                },
                "end": {
                    "line": 506,
                    "character": 46
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "\"save\" is not a known attribute of \"None\"",
            "range": {
                "start": {
                    "line": 507,
                    "character": 26
                },
                "end": {
                    "line": 507,
                    "character": 30
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 511,
                    "character": 78
                },
                "end": {
                    "line": 511,
                    "character": 80
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\populate_comprehensive_demo_data.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 539,
                    "character": 86
                },
                "end": {
                    "line": 539,
                    "character": 88
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\test_celery.py",
            "severity": "error",
            "message": "Cannot access attribute \"delay\" for class \"FunctionType\"\n┬á┬áAttribute \"delay\" is unknown",
            "range": {
                "start": {
                    "line": 24,
                    "character": 32
                },
                "end": {
                    "line": 24,
                    "character": 37
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\management\\commands\\test_celery.py",
            "severity": "error",
            "message": "Argument missing for parameter \"self\"",
            "range": {
                "start": {
                    "line": 29,
                    "character": 21
                },
                "end": {
                    "line": 29,
                    "character": 33
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\middleware.py",
            "severity": "error",
            "message": "\"psutil\" is possibly unbound",
            "range": {
                "start": {
                    "line": 119,
                    "character": 31
                },
                "end": {
                    "line": 119,
                    "character": 37
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\middleware.py",
            "severity": "error",
            "message": "\"psutil\" is possibly unbound",
            "range": {
                "start": {
                    "line": 120,
                    "character": 34
                },
                "end": {
                    "line": 120,
                    "character": 40
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\middleware.py",
            "severity": "error",
            "message": "\"psutil\" is possibly unbound",
            "range": {
                "start": {
                    "line": 121,
                    "character": 30
                },
                "end": {
                    "line": 121,
                    "character": 36
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"core.models.Customer.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[core.models.Customer.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 81,
                    "character": 10
                },
                "end": {
                    "line": 81,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"core.models.EquipmentCategory.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[core.models.EquipmentCategory.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 114,
                    "character": 10
                },
                "end": {
                    "line": 114,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"core.models.Location.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[core.models.Location.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 164,
                    "character": 10
                },
                "end": {
                    "line": 164,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"core.models.Role.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[core.models.Role.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 291,
                    "character": 10
                },
                "end": {
                    "line": 291,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"core.models.ModelDocument.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[core.models.ModelDocument.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 487,
                    "character": 10
                },
                "end": {
                    "line": 487,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\signals.py",
            "severity": "error",
            "message": "\"objects\" is not a known attribute of \"None\"",
            "range": {
                "start": {
                    "line": 64,
                    "character": 91
                },
                "end": {
                    "line": 64,
                    "character": 98
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\signals.py",
            "severity": "error",
            "message": "Cannot access attribute \"objects\" for class \"Literal['self']\"\n┬á┬áAttribute \"objects\" is unknown",
            "range": {
                "start": {
                    "line": 64,
                    "character": 91
                },
                "end": {
                    "line": 64,
                    "character": 98
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\tasks.py",
            "severity": "error",
            "message": "\"log\" is possibly unbound",
            "range": {
                "start": {
                    "line": 62,
                    "character": 12
                },
                "end": {
                    "line": 62,
                    "character": 15
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\tasks.py",
            "severity": "error",
            "message": "\"log\" is possibly unbound",
            "range": {
                "start": {
                    "line": 63,
                    "character": 12
                },
                "end": {
                    "line": 63,
                    "character": 15
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\tasks.py",
            "severity": "error",
            "message": "\"log\" is possibly unbound",
            "range": {
                "start": {
                    "line": 69,
                    "character": 12
                },
                "end": {
                    "line": 69,
                    "character": 15
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\tasks.py",
            "severity": "error",
            "message": "\"log\" is possibly unbound",
            "range": {
                "start": {
                    "line": 70,
                    "character": 12
                },
                "end": {
                    "line": 70,
                    "character": 15
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "No overloads for \"path\" match the provided arguments",
            "range": {
                "start": {
                    "line": 54,
                    "character": 4
                },
                "end": {
                    "line": 54,
                    "character": 69
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"view\" of type \"Sequence[URLResolver | str]\" in function \"path\"\n┬á┬á\"FunctionType\" is not assignable to \"Sequence[URLResolver | str]\"",
            "range": {
                "start": {
                    "line": 54,
                    "character": 27
                },
                "end": {
                    "line": 54,
                    "character": 46
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "No overloads for \"path\" match the provided arguments",
            "range": {
                "start": {
                    "line": 56,
                    "character": 4
                },
                "end": {
                    "line": 56,
                    "character": 57
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"view\" of type \"Sequence[URLResolver | str]\" in function \"path\"\n┬á┬á\"FunctionType\" is not assignable to \"Sequence[URLResolver | str]\"",
            "range": {
                "start": {
                    "line": 56,
                    "character": 23
                },
                "end": {
                    "line": 56,
                    "character": 38
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "No overloads for \"path\" match the provided arguments",
            "range": {
                "start": {
                    "line": 58,
                    "character": 4
                },
                "end": {
                    "line": 58,
                    "character": 87
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"view\" of type \"Sequence[URLResolver | str]\" in function \"path\"\n┬á┬á\"FunctionType\" is not assignable to \"Sequence[URLResolver | str]\"",
            "range": {
                "start": {
                    "line": 58,
                    "character": 33
                },
                "end": {
                    "line": 58,
                    "character": 58
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "No overloads for \"path\" match the provided arguments",
            "range": {
                "start": {
                    "line": 59,
                    "character": 4
                },
                "end": {
                    "line": 59,
                    "character": 57
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"view\" of type \"Sequence[URLResolver | str]\" in function \"path\"\n┬á┬á\"FunctionType\" is not assignable to \"Sequence[URLResolver | str]\"",
            "range": {
                "start": {
                    "line": 59,
                    "character": 23
                },
                "end": {
                    "line": 59,
                    "character": 38
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "No overloads for \"path\" match the provided arguments",
            "range": {
                "start": {
                    "line": 86,
                    "character": 4
                },
                "end": {
                    "line": 86,
                    "character": 90
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\urls.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"view\" of type \"Sequence[URLResolver | str]\" in function \"path\"\n┬á┬á\"FunctionType\" is not assignable to \"Sequence[URLResolver | str]\"",
            "range": {
                "start": {
                    "line": 86,
                    "character": 34
                },
                "end": {
                    "line": 86,
                    "character": 60
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Type \"LazySettings\" is not assignable to declared type \"(request: Unknown) -> HttpResponse\"\n┬á┬áType \"LazySettings\" is not assignable to type \"(request: Unknown) -> HttpResponse\"",
            "range": {
                "start": {
                    "line": 25,
                    "character": 24
                },
                "end": {
                    "line": 25,
                    "character": 32
                }
            },
            "rule": "reportAssignmentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 187,
                    "character": 29
                },
                "end": {
                    "line": 187,
                    "character": 31
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 188,
                    "character": 31
                },
                "end": {
                    "line": 188,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 189,
                    "character": 28
                },
                "end": {
                    "line": 189,
                    "character": 30
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 208,
                    "character": 60
                },
                "end": {
                    "line": 208,
                    "character": 62
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 209,
                    "character": 64
                },
                "end": {
                    "line": 209,
                    "character": 66
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 210,
                    "character": 58
                },
                "end": {
                    "line": 210,
                    "character": 60
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "No overloads for \"login_required\" match the provided arguments",
            "range": {
                "start": {
                    "line": 688,
                    "character": 1
                },
                "end": {
                    "line": 688,
                    "character": 15
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"function\" of type \"_VIEW@login_required\" in function \"login_required\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 688,
                    "character": 1
                },
                "end": {
                    "line": 688,
                    "character": 15
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter of type \"_VIEW@user_passes_test\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 689,
                    "character": 1
                },
                "end": {
                    "line": 689,
                    "character": 40
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 751,
                    "character": 31
                },
                "end": {
                    "line": 751,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 785,
                    "character": 88
                },
                "end": {
                    "line": 785,
                    "character": 90
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"parent_location_id\" for class \"Location\"\n┬á┬áAttribute \"parent_location_id\" is unknown",
            "range": {
                "start": {
                    "line": 790,
                    "character": 77
                },
                "end": {
                    "line": 790,
                    "character": 95
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 795,
                    "character": 38
                },
                "end": {
                    "line": 795,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"customer_id\" for class \"Location\"\n┬á┬áAttribute \"customer_id\" is unknown",
            "range": {
                "start": {
                    "line": 807,
                    "character": 25
                },
                "end": {
                    "line": 807,
                    "character": 36
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"parent_location_id\" for class \"Location\"\n┬á┬áAttribute \"parent_location_id\" is unknown",
            "range": {
                "start": {
                    "line": 811,
                    "character": 25
                },
                "end": {
                    "line": 811,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"equipment\" for class \"Location\"\n┬á┬áAttribute \"equipment\" is unknown",
            "range": {
                "start": {
                    "line": 834,
                    "character": 59
                },
                "end": {
                    "line": 834,
                    "character": 68
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"child_locations\" for class \"Location\"\n┬á┬áAttribute \"child_locations\" is unknown",
            "range": {
                "start": {
                    "line": 839,
                    "character": 24
                },
                "end": {
                    "line": 839,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "No overloads for \"login_required\" match the provided arguments",
            "range": {
                "start": {
                    "line": 855,
                    "character": 1
                },
                "end": {
                    "line": 855,
                    "character": 15
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"function\" of type \"_VIEW@login_required\" in function \"login_required\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 855,
                    "character": 1
                },
                "end": {
                    "line": 855,
                    "character": 15
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter of type \"_VIEW@user_passes_test\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 856,
                    "character": 1
                },
                "end": {
                    "line": 856,
                    "character": 40
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "No overloads for \"login_required\" match the provided arguments",
            "range": {
                "start": {
                    "line": 867,
                    "character": 1
                },
                "end": {
                    "line": 867,
                    "character": 15
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"function\" of type \"_VIEW@login_required\" in function \"login_required\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 867,
                    "character": 1
                },
                "end": {
                    "line": 867,
                    "character": 15
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter of type \"_VIEW@user_passes_test\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 868,
                    "character": 1
                },
                "end": {
                    "line": 868,
                    "character": 40
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Role\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 912,
                    "character": 23
                },
                "end": {
                    "line": 912,
                    "character": 25
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Role\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 940,
                    "character": 62
                },
                "end": {
                    "line": 940,
                    "character": 64
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "No overloads for \"login_required\" match the provided arguments",
            "range": {
                "start": {
                    "line": 985,
                    "character": 1
                },
                "end": {
                    "line": 985,
                    "character": 15
                }
            },
            "rule": "reportCallIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter \"function\" of type \"_VIEW@login_required\" in function \"login_required\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 985,
                    "character": 1
                },
                "end": {
                    "line": 985,
                    "character": 15
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Argument of type \"(request: Unknown) -> (JsonResponse | None)\" cannot be assigned to parameter of type \"_VIEW@user_passes_test\"\n┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬áType \"(request: Unknown) -> (JsonResponse | None)\" is not assignable to type \"(...) -> (HttpResponseBase | Awaitable[HttpResponseBase])\"\n┬á┬á┬á┬á┬á┬áFunction return type \"JsonResponse | None\" is incompatible with type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬áType \"JsonResponse | None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"\n┬á┬á┬á┬á┬á┬á┬á┬á┬á┬áType \"None\" is not assignable to type \"HttpResponseBase | Awaitable[HttpResponseBase]\"",
            "range": {
                "start": {
                    "line": 986,
                    "character": 1
                },
                "end": {
                    "line": 986,
                    "character": 40
                }
            },
            "rule": "reportArgumentType"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Role\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1035,
                    "character": 27
                },
                "end": {
                    "line": 1035,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "\"io\" is not defined",
            "range": {
                "start": {
                    "line": 1222,
                    "character": 30
                },
                "end": {
                    "line": 1222,
                    "character": 32
                }
            },
            "rule": "reportUndefinedVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"equipment\" for class \"Location\"\n┬á┬áAttribute \"equipment\" is unknown",
            "range": {
                "start": {
                    "line": 1320,
                    "character": 20
                },
                "end": {
                    "line": 1320,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"child_locations\" for class \"Location\"\n┬á┬áAttribute \"child_locations\" is unknown",
            "range": {
                "start": {
                    "line": 1324,
                    "character": 20
                },
                "end": {
                    "line": 1324,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"equipment\" for class \"EquipmentCategory\"\n┬á┬áAttribute \"equipment\" is unknown",
            "range": {
                "start": {
                    "line": 1346,
                    "character": 20
                },
                "end": {
                    "line": 1346,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "\"io\" is not defined",
            "range": {
                "start": {
                    "line": 1425,
                    "character": 30
                },
                "end": {
                    "line": 1425,
                    "character": 32
                }
            },
            "rule": "reportUndefinedVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"locations\" for class \"Customer\"\n┬á┬áAttribute \"locations\" is unknown",
            "range": {
                "start": {
                    "line": 1643,
                    "character": 34
                },
                "end": {
                    "line": 1643,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"locations\" for class \"Customer\"\n┬á┬áAttribute \"locations\" is unknown",
            "range": {
                "start": {
                    "line": 1658,
                    "character": 36
                },
                "end": {
                    "line": 1658,
                    "character": 45
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"keys\" for class \"BaseCache\"\n┬á┬áAttribute \"keys\" is unknown",
            "range": {
                "start": {
                    "line": 1823,
                    "character": 25
                },
                "end": {
                    "line": 1823,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2315,
                    "character": 30
                },
                "end": {
                    "line": 2315,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"delay\" for class \"FunctionType\"\n┬á┬áAttribute \"delay\" is unknown",
            "range": {
                "start": {
                    "line": 2336,
                    "character": 29
                },
                "end": {
                    "line": 2336,
                    "character": 34
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2336,
                    "character": 39
                },
                "end": {
                    "line": 2336,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2337,
                    "character": 39
                },
                "end": {
                    "line": 2337,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"delay\" for class \"FunctionType\"\n┬á┬áAttribute \"delay\" is unknown",
            "range": {
                "start": {
                    "line": 2487,
                    "character": 50
                },
                "end": {
                    "line": 2487,
                    "character": 55
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"delay\" for class \"FunctionType\"\n┬á┬áAttribute \"delay\" is unknown",
            "range": {
                "start": {
                    "line": 2540,
                    "character": 44
                },
                "end": {
                    "line": 2540,
                    "character": 49
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2598,
                    "character": 34
                },
                "end": {
                    "line": 2598,
                    "character": 36
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2625,
                    "character": 30
                },
                "end": {
                    "line": 2625,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"created_at\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"created_at\" is unknown",
            "range": {
                "start": {
                    "line": 2630,
                    "character": 38
                },
                "end": {
                    "line": 2630,
                    "character": 48
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"delay\" for class \"FunctionType\"\n┬á┬áAttribute \"delay\" is unknown",
            "range": {
                "start": {
                    "line": 2771,
                    "character": 54
                },
                "end": {
                    "line": 2771,
                    "character": 59
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"customer_id\" for class \"Location\"\n┬á┬áAttribute \"customer_id\" is unknown",
            "range": {
                "start": {
                    "line": 2881,
                    "character": 37
                },
                "end": {
                    "line": 2881,
                    "character": 48
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"child_locations\" for class \"Location\"\n┬á┬áAttribute \"child_locations\" is unknown",
            "range": {
                "start": {
                    "line": 2927,
                    "character": 36
                },
                "end": {
                    "line": 2927,
                    "character": 51
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"equipment_set\" for class \"Location\"\n┬á┬áAttribute \"equipment_set\" is unknown",
            "range": {
                "start": {
                    "line": 2932,
                    "character": 75
                },
                "end": {
                    "line": 2932,
                    "character": 88
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 2972,
                    "character": 80
                },
                "end": {
                    "line": 2972,
                    "character": 82
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 3004,
                    "character": 30
                },
                "end": {
                    "line": 3004,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Customer\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 3005,
                    "character": 38
                },
                "end": {
                    "line": 3005,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\core\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"BASE_DIR\" for class \"FunctionType\"\n┬á┬áAttribute \"BASE_DIR\" is unknown",
            "range": {
                "start": {
                    "line": 3041,
                    "character": 40
                },
                "end": {
                    "line": 3041,
                    "character": 48
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 199,
                    "character": 23
                },
                "end": {
                    "line": 199,
                    "character": 36
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 200,
                    "character": 23
                },
                "end": {
                    "line": 200,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"processing_errors\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"processing_errors\" is unknown",
            "range": {
                "start": {
                    "line": 214,
                    "character": 23
                },
                "end": {
                    "line": 214,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "\"analyze_report_content\" is possibly unbound",
            "range": {
                "start": {
                    "line": 268,
                    "character": 28
                },
                "end": {
                    "line": 268,
                    "character": 50
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 269,
                    "character": 26
                },
                "end": {
                    "line": 269,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 270,
                    "character": 26
                },
                "end": {
                    "line": 270,
                    "character": 38
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_demo_reports.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"processing_errors\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"processing_errors\" is unknown",
            "range": {
                "start": {
                    "line": 284,
                    "character": 26
                },
                "end": {
                    "line": 284,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_equipment_sophie.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 19,
                    "character": 84
                },
                "end": {
                    "line": 19,
                    "character": 86
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_equipment_sophie.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"Equipment\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 56,
                    "character": 38
                },
                "end": {
                    "line": 56,
                    "character": 56
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_equipment_sophie.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 67,
                    "character": 46
                },
                "end": {
                    "line": 67,
                    "character": 48
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\create_test_prompt.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"PlaywrightDebugLog\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 19,
                    "character": 65
                },
                "end": {
                    "line": 19,
                    "character": 67
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"short_description\" for class \"FunctionType\"\n┬á┬áAttribute \"short_description\" is unknown",
            "range": {
                "start": {
                    "line": 43,
                    "character": 13
                },
                "end": {
                    "line": 43,
                    "character": 30
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"admin_order_field\" for class \"FunctionType\"\n┬á┬áAttribute \"admin_order_field\" is unknown",
            "range": {
                "start": {
                    "line": 44,
                    "character": 13
                },
                "end": {
                    "line": 44,
                    "character": 30
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 36,
                    "character": 32
                },
                "end": {
                    "line": 36,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 37,
                    "character": 32
                },
                "end": {
                    "line": 37,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"equipment.models.Equipment.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[equipment.models.Equipment.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 105,
                    "character": 10
                },
                "end": {
                    "line": 105,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"Equipment*\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 117,
                    "character": 36
                },
                "end": {
                    "line": 117,
                    "character": 54
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"maintenance_activities\" for class \"Equipment*\"\n┬á┬áAttribute \"maintenance_activities\" is unknown",
            "range": {
                "start": {
                    "line": 154,
                    "character": 29
                },
                "end": {
                    "line": 154,
                    "character": 51
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"equipment.models.EquipmentDocument.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[equipment.models.EquipmentDocument.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 226,
                    "character": 10
                },
                "end": {
                    "line": 226,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"equipment.models.EquipmentComponent.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[equipment.models.EquipmentComponent.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 261,
                    "character": 10
                },
                "end": {
                    "line": 261,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Import \"PyPDF2\" could not be resolved",
            "range": {
                "start": {
                    "line": 23,
                    "character": 11
                },
                "end": {
                    "line": 23,
                    "character": 17
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 214,
                    "character": 21
                },
                "end": {
                    "line": 214,
                    "character": 23
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"Equipment\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 219,
                    "character": 25
                },
                "end": {
                    "line": 219,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 253,
                    "character": 28
                },
                "end": {
                    "line": 253,
                    "character": 30
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"Equipment\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 259,
                    "character": 32
                },
                "end": {
                    "line": 259,
                    "character": 50
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"maintenance_activities\" for class \"Equipment\"\n┬á┬áAttribute \"maintenance_activities\" is unknown",
            "range": {
                "start": {
                    "line": 274,
                    "character": 32
                },
                "end": {
                    "line": 274,
                    "character": 54
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"maintenance_activities\" for class \"Equipment\"\n┬á┬áAttribute \"maintenance_activities\" is unknown",
            "range": {
                "start": {
                    "line": 275,
                    "character": 30
                },
                "end": {
                    "line": 275,
                    "character": 52
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"maintenance_activities\" for class \"Equipment\"\n┬á┬áAttribute \"maintenance_activities\" is unknown",
            "range": {
                "start": {
                    "line": 276,
                    "character": 30
                },
                "end": {
                    "line": 276,
                    "character": 52
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"documents\" for class \"Equipment\"\n┬á┬áAttribute \"documents\" is unknown",
            "range": {
                "start": {
                    "line": 277,
                    "character": 39
                },
                "end": {
                    "line": 277,
                    "character": 48
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 397,
                    "character": 32
                },
                "end": {
                    "line": 397,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"Equipment\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 403,
                    "character": 36
                },
                "end": {
                    "line": 403,
                    "character": 54
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 454,
                    "character": 28
                },
                "end": {
                    "line": 454,
                    "character": 30
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"components\" for class \"Equipment\"\n┬á┬áAttribute \"components\" is unknown",
            "range": {
                "start": {
                    "line": 472,
                    "character": 27
                },
                "end": {
                    "line": 472,
                    "character": 37
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 496,
                    "character": 85
                },
                "end": {
                    "line": 496,
                    "character": 87
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"documents\" for class \"Equipment\"\n┬á┬áAttribute \"documents\" is unknown",
            "range": {
                "start": {
                    "line": 512,
                    "character": 26
                },
                "end": {
                    "line": 512,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 536,
                    "character": 84
                },
                "end": {
                    "line": 536,
                    "character": 86
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Function declaration \"import_equipment_csv\" is obscured by a declaration of the same name",
            "range": {
                "start": {
                    "line": 549,
                    "character": 4
                },
                "end": {
                    "line": 549,
                    "character": 24
                }
            },
            "rule": "reportRedeclaration"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 950,
                    "character": 72
                },
                "end": {
                    "line": 950,
                    "character": 74
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_report_type_display\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"get_report_type_display\" is unknown",
            "range": {
                "start": {
                    "line": 1010,
                    "character": 42
                },
                "end": {
                    "line": 1010,
                    "character": 65
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 1014,
                    "character": 44
                },
                "end": {
                    "line": 1014,
                    "character": 62
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\equipment\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"maintenance_activities\" for class \"Equipment\"\n┬á┬áAttribute \"maintenance_activities\" is unknown",
            "range": {
                "start": {
                    "line": 1050,
                    "character": 31
                },
                "end": {
                    "line": 1050,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"events.models.CalendarEvent.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[events.models.CalendarEvent.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 101,
                    "character": 10
                },
                "end": {
                    "line": 101,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"events.models.EventComment.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[events.models.EventComment.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 156,
                    "character": 10
                },
                "end": {
                    "line": 156,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"events.models.EventAttachment.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[events.models.EventAttachment.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 183,
                    "character": 10
                },
                "end": {
                    "line": 183,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"events.models.EventReminder.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[events.models.EventReminder.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 220,
                    "character": 10
                },
                "end": {
                    "line": 220,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\tasks.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_event_type_display\" for class \"CalendarEvent\"\n┬á┬áAttribute \"get_event_type_display\" is unknown",
            "range": {
                "start": {
                    "line": 36,
                    "character": 42
                },
                "end": {
                    "line": 36,
                    "character": 64
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\tasks.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 44,
                    "character": 73
                },
                "end": {
                    "line": 44,
                    "character": 75
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\tasks.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 102,
                    "character": 80
                },
                "end": {
                    "line": 102,
                    "character": 82
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "\"timedelta\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 47,
                    "character": 102
                },
                "end": {
                    "line": 47,
                    "character": 111
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "\"timedelta\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 78,
                    "character": 66
                },
                "end": {
                    "line": 78,
                    "character": 75
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 138,
                    "character": 37
                },
                "end": {
                    "line": 138,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_event_type_display\" for class \"CalendarEvent\"\n┬á┬áAttribute \"get_event_type_display\" is unknown",
            "range": {
                "start": {
                    "line": 157,
                    "character": 38
                },
                "end": {
                    "line": 157,
                    "character": 60
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_priority_display\" for class \"CalendarEvent\"\n┬á┬áAttribute \"get_priority_display\" is unknown",
            "range": {
                "start": {
                    "line": 158,
                    "character": 42
                },
                "end": {
                    "line": 158,
                    "character": 62
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivityType\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 283,
                    "character": 61
                },
                "end": {
                    "line": 283,
                    "character": 63
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 332,
                    "character": 28
                },
                "end": {
                    "line": 332,
                    "character": 30
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 450,
                    "character": 66
                },
                "end": {
                    "line": 450,
                    "character": 68
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"comments\" for class \"CalendarEvent\"\n┬á┬áAttribute \"comments\" is unknown",
            "range": {
                "start": {
                    "line": 474,
                    "character": 21
                },
                "end": {
                    "line": 474,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"attachments\" for class \"CalendarEvent\"\n┬á┬áAttribute \"attachments\" is unknown",
            "range": {
                "start": {
                    "line": 475,
                    "character": 24
                },
                "end": {
                    "line": 475,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 487,
                    "character": 66
                },
                "end": {
                    "line": 487,
                    "character": 68
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"equipment_id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"equipment_id\" is unknown",
            "range": {
                "start": {
                    "line": 508,
                    "character": 18
                },
                "end": {
                    "line": 508,
                    "character": 30
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"assigned_to_id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"assigned_to_id\" is unknown",
            "range": {
                "start": {
                    "line": 514,
                    "character": 18
                },
                "end": {
                    "line": 514,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 529,
                    "character": 66
                },
                "end": {
                    "line": 529,
                    "character": 68
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 621,
                    "character": 32
                },
                "end": {
                    "line": 621,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 628,
                    "character": 51
                },
                "end": {
                    "line": 628,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 648,
                    "character": 54
                },
                "end": {
                    "line": 648,
                    "character": 56
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 720,
                    "character": 45
                },
                "end": {
                    "line": 720,
                    "character": 47
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 727,
                    "character": 55
                },
                "end": {
                    "line": 727,
                    "character": 57
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 747,
                    "character": 58
                },
                "end": {
                    "line": 747,
                    "character": 60
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 810,
                    "character": 51
                },
                "end": {
                    "line": 810,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 818,
                    "character": 65
                },
                "end": {
                    "line": 818,
                    "character": 67
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 833,
                    "character": 64
                },
                "end": {
                    "line": 833,
                    "character": 66
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 884,
                    "character": 20
                },
                "end": {
                    "line": 884,
                    "character": 22
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 976,
                    "character": 30
                },
                "end": {
                    "line": 976,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"equipment_id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"equipment_id\" is unknown",
            "range": {
                "start": {
                    "line": 997,
                    "character": 14
                },
                "end": {
                    "line": 997,
                    "character": 26
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"assigned_to_id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"assigned_to_id\" is unknown",
            "range": {
                "start": {
                    "line": 1003,
                    "character": 14
                },
                "end": {
                    "line": 1003,
                    "character": 28
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1017,
                    "character": 30
                },
                "end": {
                    "line": 1017,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1047,
                    "character": 32
                },
                "end": {
                    "line": 1047,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"User\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1055,
                    "character": 27
                },
                "end": {
                    "line": 1055,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"CalendarEvent\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1091,
                    "character": 32
                },
                "end": {
                    "line": 1091,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1119,
                    "character": 35
                },
                "end": {
                    "line": 1119,
                    "character": 37
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1147,
                    "character": 29
                },
                "end": {
                    "line": 1147,
                    "character": 31
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1174,
                    "character": 30
                },
                "end": {
                    "line": 1174,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"User\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1201,
                    "character": 31
                },
                "end": {
                    "line": 1201,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivityType\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1229,
                    "character": 29
                },
                "end": {
                    "line": 1229,
                    "character": 31
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\events\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"EquipmentCategory\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1256,
                    "character": 29
                },
                "end": {
                    "line": 1256,
                    "character": 31
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\generate_dga_pdf.py",
            "severity": "warning",
            "message": "Import \"reportlab.pdfgen\" could not be resolved from source",
            "range": {
                "start": {
                    "line": 3,
                    "character": 5
                },
                "end": {
                    "line": 3,
                    "character": 21
                }
            },
            "rule": "reportMissingModuleSource"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\generate_dga_pdf.py",
            "severity": "warning",
            "message": "Import \"reportlab.pdfgen.canvas\" could not be resolved from source",
            "range": {
                "start": {
                    "line": 3,
                    "character": 29
                },
                "end": {
                    "line": 3,
                    "character": 35
                }
            },
            "rule": "reportMissingModuleSource"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\generate_dga_pdf.py",
            "severity": "warning",
            "message": "Import \"reportlab.lib.pagesizes\" could not be resolved from source",
            "range": {
                "start": {
                    "line": 4,
                    "character": 5
                },
                "end": {
                    "line": 4,
                    "character": 28
                }
            },
            "rule": "reportMissingModuleSource"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"boolean\" for class \"FunctionType\"\n┬á┬áAttribute \"boolean\" is unknown",
            "range": {
                "start": {
                    "line": 265,
                    "character": 24
                },
                "end": {
                    "line": 265,
                    "character": 31
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\admin.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"short_description\" for class \"FunctionType\"\n┬á┬áAttribute \"short_description\" is unknown",
            "range": {
                "start": {
                    "line": 266,
                    "character": 24
                },
                "end": {
                    "line": 266,
                    "character": 41
                }
            },
            "rule": "reportFunctionMemberAccess"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 75,
                    "character": 42
                },
                "end": {
                    "line": 75,
                    "character": 50
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 76,
                    "character": 32
                },
                "end": {
                    "line": 76,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 156,
                    "character": 32
                },
                "end": {
                    "line": 156,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 157,
                    "character": 32
                },
                "end": {
                    "line": 157,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 158,
                    "character": 55
                },
                "end": {
                    "line": 158,
                    "character": 63
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 159,
                    "character": 42
                },
                "end": {
                    "line": 159,
                    "character": 50
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 255,
                    "character": 33
                },
                "end": {
                    "line": 255,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 256,
                    "character": 37
                },
                "end": {
                    "line": 256,
                    "character": 45
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 257,
                    "character": 35
                },
                "end": {
                    "line": 257,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 339,
                    "character": 33
                },
                "end": {
                    "line": 339,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\forms.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 340,
                    "character": 37
                },
                "end": {
                    "line": 340,
                    "character": 45
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.ActivityTypeCategory.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.ActivityTypeCategory.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 27,
                    "character": 10
                },
                "end": {
                    "line": 27,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.ActivityTypeTemplate.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.ActivityTypeTemplate.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 70,
                    "character": 10
                },
                "end": {
                    "line": 70,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceActivityType.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceActivityType.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 127,
                    "character": 10
                },
                "end": {
                    "line": 127,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceActivity.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceActivity.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 218,
                    "character": 10
                },
                "end": {
                    "line": 218,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"MaintenanceActivity*\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 229,
                    "character": 61
                },
                "end": {
                    "line": 229,
                    "character": 79
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceChecklist.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceChecklist.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 316,
                    "character": 10
                },
                "end": {
                    "line": 316,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceSchedule.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceSchedule.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 388,
                    "character": 10
                },
                "end": {
                    "line": 388,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_frequency_display\" for class \"MaintenanceSchedule*\"\n┬á┬áAttribute \"get_frequency_display\" is unknown",
            "range": {
                "start": {
                    "line": 395,
                    "character": 74
                },
                "end": {
                    "line": 395,
                    "character": 95
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"datetime\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 445,
                    "character": 45
                },
                "end": {
                    "line": 445,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"datetime\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 447,
                    "character": 33
                },
                "end": {
                    "line": 447,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"datetime\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 449,
                    "character": 43
                },
                "end": {
                    "line": 449,
                    "character": 51
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"datetime\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 451,
                    "character": 33
                },
                "end": {
                    "line": 451,
                    "character": 41
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 481,
                    "character": 98
                },
                "end": {
                    "line": 481,
                    "character": 100
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceTimelineEntry.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceTimelineEntry.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 544,
                    "character": 10
                },
                "end": {
                    "line": 544,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "\"Meta\" overrides symbol of same name in class \"TimeStampedModel\"\n┬á┬á\"maintenance.models.MaintenanceReport.Meta\" is not assignable to \"core.models.TimeStampedModel.Meta\"\n┬á┬áType \"type[maintenance.models.MaintenanceReport.Meta]\" is not assignable to type \"type[core.models.TimeStampedModel.Meta]\"",
            "range": {
                "start": {
                    "line": 663,
                    "character": 10
                },
                "end": {
                    "line": 663,
                    "character": 14
                }
            },
            "rule": "reportIncompatibleVariableOverride"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 716,
                    "character": 16
                },
                "end": {
                    "line": 716,
                    "character": 24
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 717,
                    "character": 24
                },
                "end": {
                    "line": 717,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 722,
                    "character": 16
                },
                "end": {
                    "line": 722,
                    "character": 24
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 722,
                    "character": 34
                },
                "end": {
                    "line": 722,
                    "character": 42
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 722,
                    "character": 63
                },
                "end": {
                    "line": 722,
                    "character": 71
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"document\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"document\" is unknown",
            "range": {
                "start": {
                    "line": 723,
                    "character": 24
                },
                "end": {
                    "line": 723,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 740,
                    "character": 20
                },
                "end": {
                    "line": 740,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 744,
                    "character": 20
                },
                "end": {
                    "line": 744,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\models.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport*\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 748,
                    "character": 20
                },
                "end": {
                    "line": 748,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\tasks.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceSchedule\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 31,
                    "character": 76
                },
                "end": {
                    "line": 31,
                    "character": 78
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\tasks.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 67,
                    "character": 73
                },
                "end": {
                    "line": 67,
                    "character": 75
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"checklist_items\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"checklist_items\" is unknown",
            "range": {
                "start": {
                    "line": 275,
                    "character": 31
                },
                "end": {
                    "line": 275,
                    "character": 46
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"queryset\" for class \"Field\"\n┬á┬áAttribute \"queryset\" is unknown",
            "range": {
                "start": {
                    "line": 334,
                    "character": 58
                },
                "end": {
                    "line": 334,
                    "character": 66
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 442,
                    "character": 76
                },
                "end": {
                    "line": 442,
                    "character": 78
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "\"timedelta\" is not a known attribute of module \"django.utils.timezone\"",
            "range": {
                "start": {
                    "line": 958,
                    "character": 70
                },
                "end": {
                    "line": 958,
                    "character": 79
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1168,
                    "character": 27
                },
                "end": {
                    "line": 1168,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"ActivityTypeTemplate\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1414,
                    "character": 27
                },
                "end": {
                    "line": 1414,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"ActivityTypeTemplate\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1438,
                    "character": 23
                },
                "end": {
                    "line": 1438,
                    "character": 25
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivityType\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1476,
                    "character": 36
                },
                "end": {
                    "line": 1476,
                    "character": 38
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivityType\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1540,
                    "character": 46
                },
                "end": {
                    "line": 1540,
                    "character": 48
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1581,
                    "character": 31
                },
                "end": {
                    "line": 1581,
                    "character": 33
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"checklist_items\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"checklist_items\" is unknown",
            "range": {
                "start": {
                    "line": 1610,
                    "character": 35
                },
                "end": {
                    "line": 1610,
                    "character": 50
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"timeline_entries\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"timeline_entries\" is unknown",
            "range": {
                "start": {
                    "line": 1611,
                    "character": 36
                },
                "end": {
                    "line": 1611,
                    "character": 52
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"reports\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"reports\" is unknown",
            "range": {
                "start": {
                    "line": 1612,
                    "character": 27
                },
                "end": {
                    "line": 1612,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1615,
                    "character": 27
                },
                "end": {
                    "line": 1615,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_status_display\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"get_status_display\" is unknown",
            "range": {
                "start": {
                    "line": 1618,
                    "character": 31
                },
                "end": {
                    "line": 1618,
                    "character": 49
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_priority_display\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"get_priority_display\" is unknown",
            "range": {
                "start": {
                    "line": 1619,
                    "character": 33
                },
                "end": {
                    "line": 1619,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"REPORT_TYPES\" for class \"type[MaintenanceReport]\"\n┬á┬áAttribute \"REPORT_TYPES\" is unknown",
            "range": {
                "start": {
                    "line": 1716,
                    "character": 46
                },
                "end": {
                    "line": 1716,
                    "character": 58
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 1780,
                    "character": 23
                },
                "end": {
                    "line": 1780,
                    "character": 36
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 1781,
                    "character": 23
                },
                "end": {
                    "line": 1781,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1784,
                    "character": 63
                },
                "end": {
                    "line": 1784,
                    "character": 65
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"processing_errors\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"processing_errors\" is unknown",
            "range": {
                "start": {
                    "line": 1785,
                    "character": 23
                },
                "end": {
                    "line": 1785,
                    "character": 40
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1790,
                    "character": 32
                },
                "end": {
                    "line": 1790,
                    "character": 34
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"content\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"content\" is unknown",
            "range": {
                "start": {
                    "line": 1806,
                    "character": 22
                },
                "end": {
                    "line": 1806,
                    "character": 29
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"content\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"content\" is unknown",
            "range": {
                "start": {
                    "line": 1810,
                    "character": 54
                },
                "end": {
                    "line": 1810,
                    "character": 61
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 1813,
                    "character": 15
                },
                "end": {
                    "line": 1813,
                    "character": 28
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 1814,
                    "character": 15
                },
                "end": {
                    "line": 1814,
                    "character": 27
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot assign to attribute \"processing_errors\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"processing_errors\" is unknown",
            "range": {
                "start": {
                    "line": 1815,
                    "character": 15
                },
                "end": {
                    "line": 1815,
                    "character": 32
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 1967,
                    "character": 33
                },
                "end": {
                    "line": 1967,
                    "character": 35
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_report_type_display\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"get_report_type_display\" is unknown",
            "range": {
                "start": {
                    "line": 1969,
                    "character": 42
                },
                "end": {
                    "line": 1969,
                    "character": 65
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"uploaded_by\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"uploaded_by\" is unknown",
            "range": {
                "start": {
                    "line": 1971,
                    "character": 42
                },
                "end": {
                    "line": 1971,
                    "character": 53
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"uploaded_by\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"uploaded_by\" is unknown",
            "range": {
                "start": {
                    "line": 1971,
                    "character": 73
                },
                "end": {
                    "line": 1971,
                    "character": 84
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance\\views.py",
            "severity": "error",
            "message": "Cannot access attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 1972,
                    "character": 43
                },
                "end": {
                    "line": 1972,
                    "character": 55
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\maintenance_dashboard\\settings.py",
            "severity": "error",
            "message": "Cannot access attribute \"split\" for class \"Literal[True]\"\n┬á┬áAttribute \"split\" is unknown",
            "range": {
                "start": {
                    "line": 183,
                    "character": 81
                },
                "end": {
                    "line": 183,
                    "character": 86
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\optimize_performance.py",
            "severity": "error",
            "message": "Cannot access attribute \"get_stats\" for class \"BaseCache\"\n┬á┬áAttribute \"get_stats\" is unknown",
            "range": {
                "start": {
                    "line": 92,
                    "character": 27
                },
                "end": {
                    "line": 92,
                    "character": 36
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\optimize_performance.py",
            "severity": "error",
            "message": "\"Equipment\" is unknown import symbol",
            "range": {
                "start": {
                    "line": 149,
                    "character": 42
                },
                "end": {
                    "line": 149,
                    "character": 51
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\rebase_and_test.py",
            "severity": "error",
            "message": "\"backup_branch\" is possibly unbound",
            "range": {
                "start": {
                    "line": 292,
                    "character": 59
                },
                "end": {
                    "line": 292,
                    "character": 72
                }
            },
            "rule": "reportPossiblyUnboundVariable"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_generate_pods.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Location\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 27,
                    "character": 43
                },
                "end": {
                    "line": 27,
                    "character": 45
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_generate_pods.py",
            "severity": "error",
            "message": "Cannot access attribute \"child_locations\" for class \"Location\"\n┬á┬áAttribute \"child_locations\" is unknown",
            "range": {
                "start": {
                    "line": 71,
                    "character": 28
                },
                "end": {
                    "line": 71,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"content\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"content\" is unknown",
            "range": {
                "start": {
                    "line": 65,
                    "character": 32
                },
                "end": {
                    "line": 65,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"uploaded_by\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"uploaded_by\" is unknown",
            "range": {
                "start": {
                    "line": 66,
                    "character": 32
                },
                "end": {
                    "line": 66,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 67,
                    "character": 32
                },
                "end": {
                    "line": 67,
                    "character": 44
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 68,
                    "character": 32
                },
                "end": {
                    "line": 68,
                    "character": 45
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 245,
                    "character": 85
                },
                "end": {
                    "line": 245,
                    "character": 87
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceActivity\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 253,
                    "character": 41
                },
                "end": {
                    "line": 253,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"content\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"content\" is unknown",
            "range": {
                "start": {
                    "line": 267,
                    "character": 32
                },
                "end": {
                    "line": 267,
                    "character": 39
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 280,
                    "character": 87
                },
                "end": {
                    "line": 280,
                    "character": 89
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"is_processed\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"is_processed\" is unknown",
            "range": {
                "start": {
                    "line": 288,
                    "character": 31
                },
                "end": {
                    "line": 288,
                    "character": 43
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 289,
                    "character": 39
                },
                "end": {
                    "line": 289,
                    "character": 52
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"analyzed_data\" for class \"MaintenanceReport\"\n┬á┬áAttribute \"analyzed_data\" is unknown",
            "range": {
                "start": {
                    "line": 290,
                    "character": 47
                },
                "end": {
                    "line": 290,
                    "character": 60
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Cannot access attribute \"id\" for class \"Equipment\"\n┬á┬áAttribute \"id\" is unknown",
            "range": {
                "start": {
                    "line": 302,
                    "character": 105
                },
                "end": {
                    "line": 302,
                    "character": 107
                }
            },
            "rule": "reportAttributeAccessIssue"
        },
        {
            "file": "c:\\Users\\erikw\\OneDrive\\Documents\\Projects\\Work\\Github\\New folder\\MaintDashboard\\test_maintenance_reports.py",
            "severity": "error",
            "message": "Argument of type \"int\" cannot be assigned to parameter \"obj\" of type \"Sized\" in function \"len\"\n┬á┬á\"int\" is incompatible with protocol \"Sized\"\n┬á┬á┬á┬á\"__len__\" is not present",
            "range": {
                "start": {
                    "line": 462,
                    "character": 25
                },
                "end": {
                    "line": 462,
                    "character": 33
                }
            },
            "rule": "reportArgumentType"
        }
    ],
    "summary": {
        "filesAnalyzed": 106,
        "errorCount": 276,
        "warningCount": 3,
        "informationCount": 0,
        "timeInSec": 3.821
    }
}

